# Override agent config only; other configs inherit from verl defaults

mode: async

# [Experimental] agent flow based rollout configs
agent:

  _target_: arft.config.AgentFlowConfig

  # Number of agent flow workers
  num_workers: 8

  # default agent flow to use if `agent_name` not set in RL dataset
  default_agent_flow: single_step_single_turn_agent

  # custom agent flow config path
  agent_flow_config_path: null

  # custom async server configs
  custom_async_server:

    # Required when using verl.utils.omega_conf_to_dataclass to instantiate dataclass configs
    _target_: verl.workers.config.CustomAsyncServerConfig

    # Path to the custom async server implementation
    path: null

    # Class name of the custom async server class (e.g. AsyncvLLMServer)
    name: null

